apiVersion: v1
kind: Service
metadata:
  name: sentinel-ecobee
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: ecobee
    context: sentinel-services
    version: v1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentinel-ecobee
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ecobee
        context: sentinel-services
        version: v1
    spec:
      containers:
        -
          name: sentinel-ecobee
          image: docker.steventaylor.me/sentinel/services/ecobee/ecobee-x86_64:latest
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "5000"
          - name: CONSUL
            value: "consul"
          ports:
            -
              containerPort: 5000
              protocol: TCP
      imagePullSecrets:
      - name: regcred
      nodeSelector:
          beta.kubernetes.io/arch: amd64