apiVersion: v1
kind: Service
metadata:
  name: sentinel-nest
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: nest
    context: sentinel-services
    version: v1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentinel-nest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nest
        context: sentinel-services
        version: v1
    spec:
      containers:
        -
          name: sentinel-nest
          image: docker.steventaylor.me/sentinel-nest-x86_64:latest
          imagePullPolicy: Always
          env:
            -
              name: "PORT"
              value: "5000"
            -
              name: "CONSUL"
              value: "consul.steventaylor.me"
          ports:
            -
              containerPort: 5000
              protocol: TCP
      nodeSelector:
          beta.kubernetes.io/arch: amd64